DROP TABLE "USER_INFO" CASCADE CONSTRAINTS;

CREATE TABLE "USER_INFO" (
	"USER_CODE"	NUMBER(10)		NOT NULL,
	"USER_NAME"	VARCHAR2(50)		NOT NULL,
	"PRODUCTION_DATE"	VARCHAR2(10)		NOT NULL,
	"ID"	VARCHAR2(20)		NOT NULL,
	"PW"	VARCHAR2(50)		NOT NULL
);

DROP TABLE "AC_INFO" CASCADE CONSTRAINTS;

CREATE TABLE "AC_INFO" (
	"AC_NUMBER"	VARCHAR2(7)		NOT NULL,
	"HOLDING_AMOUNT"	NUMBER(10)		NOT NULL,
	"AC_TYPE"	NUMBER(1)		NOT NULL
);

DROP TABLE "USER_AC" CASCADE CONSTRAINTS;

CREATE TABLE "USER_AC" (
	"USER_CODE"	NUMBER(10)		NOT NULL,
	"AC_NUMBER"	VARCHAR2(7)		NOT NULL
);

DROP TABLE "AC_TRADE" CASCADE CONSTRAINTS;

CREATE TABLE "AC_TRADE" (
	"TRANSACTION_NUMBER"	NUMBER(38)		NOT NULL,
	"AC_NUMBER_IN"	VARCHAR2(7)		NOT NULL,
	"AC_NUMBER_OUT"	VARCHAR2(7)		NOT NULL,
	"TRANSACTION_TIME"	VARCHAR2(50)		NOT NULL,
	"MONEY"	NUMBER(38)		NOT NULL,
	"TRANSACTION_METHOD"	NUMBER(38)		NOT NULL
);

ALTER TABLE "USER_INFO" ADD CONSTRAINT "PK_USER_INFO" PRIMARY KEY (
	"USER_CODE"
);

ALTER TABLE "AC_INFO" ADD CONSTRAINT "PK_AC_INFO" PRIMARY KEY (
	"AC_NUMBER"
);

ALTER TABLE "USER_AC" ADD CONSTRAINT "PK_USER_AC" PRIMARY KEY (
	"USER_CODE",
	"AC_NUMBER"
);

ALTER TABLE "AC_TRADE" ADD CONSTRAINT "PK_AC_TRADE" PRIMARY KEY (
	"TRANSACTION_NUMBER"
);

ALTER TABLE "USER_AC" ADD CONSTRAINT "FK_USER_INFO_TO_USER_AC_1" FOREIGN KEY (
	"USER_CODE"
)
REFERENCES "USER_INFO" (
	"USER_CODE"
);

ALTER TABLE "USER_AC" ADD CONSTRAINT "FK_AC_INFO_TO_USER_AC_1" FOREIGN KEY (
	"AC_NUMBER"
)
REFERENCES "AC_INFO" (
	"AC_NUMBER"
);

INSERT INTO USER_INFO VALUES(20501,'강동현',TO_DATE('2003-01-01','YYYY-MM-DD'),'kang1','kang1');
INSERT INTO USER_INFO VALUES(20502,'강응찬',TO_DATE('2003-01-02','YYYY-MM-DD'),'kang2','kang2');

INSERT INTO AC_INFO VALUES('110-001',100000,1);
INSERT INTO AC_INFO VALUES('110-002',100000,1);

INSERT INTO USER_AC VALUES(20501,'110-001');
INSERT INTO USER_AC VALUES(20502,'110-002');

SELECT * FROM USER_INFO;
SELECT * FROM AC_INFO;
SELECT * FROM USER_AC;

SELECT AC_NUMBER, HOLDING_AMOUNT, AC_TYPE FROM AC_INFO;
SELECT * FROM USER_INFO WHERE USER_CODE = 20501
SELECT AC_NUMBER FROM USER_AC WHERE USER_CODE = 20501;
SELECT AC_NUMBER